GET http://localhost:3000/api/search?q=Stanford

###
GET http://localhost:3000/api/search?q=San%20Jose%20State

###
POST http://localhost:3000/api/mycolleges
Content-Type: application/json

{
    "email": "soma.ellappan@gmail.com",
    "collegeId": "12345"
}


###

POST http://localhost:3000/api/users
Content-Type: application/json

{
    "fullName": "Soma Ellappan",
    "email": "soma.ellappan@gmail.com",
    "password": "password123"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json  

{
    "email": "soma.ellappan@gmail.com",
    "password": "password123"
}

###
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNvbWEuZWxsYXBwYW5AZ21haWwuY29tIiwiaWQiOiI2ODg2ZTgwNzZiNTE5NzY3MDU2ZGM0MWQiLCJpYXQiOjE3NTM3Njk1OTQsImV4cCI6MTc1Mzc2OTg5NH0.cNFCbj79vzJDXiAWjDS7q_kEHwYo6n1gYpboVJAk8DU

###
POST http://localhost:3000/api/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNvbWEuZWxsYXBwYW5AZ21haWwuY29tIiwiaWQiOiI2ODg0NTc3YWI1OWQzMWM5MzU4N2NmN2MiLCJpYXQiOjE3NTM1MDY2ODYsImV4cCI6MTc1MzUwNjk4Nn0.9Zrt3IFqV2_d-4FYJtdpP_lAeAT9qZg1sYrzPJU5Fo8

{
    "firstMajor": "Computer Science",
    "secondMajor": "Math",
    "satEnglish": "750",
    "satMath": "800",
    "act": "36"
}

###
GET http://localhost:3000/api/auth/accesstoken

###
POST http://localhost:3000/api/auth/logout

###
GET http://localhost:3000/api/users

###
DELETE http://localhost:3000/api/users
Content-Type: application/json

{
    "email": "soma.ellappan@gmail.com"
}
